POST http://localhost:4000/owner_channel_video
Content-Type: application/json

{
  "owner_id":40,
  "owner_name":"a",
  "channel":{
    "channel_id":4000,
    "channel_name":"aaaaaa",
    "videos":[
      {"video_id":422,
      "video_title":"a1"},
      {"video_id":433,
      "video_title":"a2"}
    ]
  }
}

###
GET http://localhost:4000/owner_channel_video